name: Hello World
author: Fred
description: some description
inputs:
  who-to-great:
    description: 'who to great'
    required: true
    default: Ali
outputs:
  time:
    description: 'The greeting time'
runs:
  using: 'docker'
  image: 'Dockerfile'
#  entrypoint:
  args:
    - ${{ inputs.who-to-great }}

